[package]
name = "piet-glow"
version = "0.1.0"
edition = "2021"
authors = ["John Nunley <jtnunley01@gmail.com>"]
description = "A Piet renderer that uses OpenGL"

[dependencies]
ahash = "0.8.3"
glow = { version = "0.12.0", default-features = false }
piet = { version = "0.6.2", default-features = false }
