[package]
name = "piet-glow"
version = "0.1.0"
edition = "2021"
authors = ["John Nunley <jtnunley01@gmail.com>"]
description = "A Piet renderer that uses OpenGL"

[dependencies]
arrayvec = "0.7.2"
bytemuck = { version = "1.13.0", default-features = false }
euclid = { version = "0.22.7", default-features = false, features = ["bytemuck"] }
glow = { version = "0.12.0", default-features = false }
lyon_tessellation = { version = "1.0.10", default-features = false }
piet = { version = "0.6.2", default-features = false }
tinyvec = { version = "1.6.0", default-features = false, features = ["alloc"] }

[dev-dependencies]
glutin = "0.30.6"
glutin-winit = "0.3.0"
raw-window-handle = "0.5.0"
winit = "0.28.1"
