[package]
name = "piet-glow"
version = "0.1.0"
edition = "2021"
authors = ["John Nunley <jtnunley01@gmail.com>"]
description = "A Piet renderer that uses OpenGL"

[dependencies]
glow = { version = "0.12.0", default-features = false }
piet = { version = "0.6.2", default-features = false }
tinyvec = { version = "1.6.0", default-features = false, features = ["alloc"] }
